### ISSUE TITLE
Missing namespace in RBAC ServiceAccount

### ISSUE THREAD

**Issue by CyberHippo** [niqdev/lastpass-operator#2]
The RBAC templates to create the ServiceAccount do not take into account the namespace specified in the values.yaml. This causes the ServiceAccount to be created in the namespace where the Helm command is performed and not in the desired namespace.

I think it should be changed from:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
```
to:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
```
