### ISSUE TITLE
Support creation of dockerconfigjson secret type

### ISSUE THREAD

**Issue by conorfennell** [niqdev/lastpass-operator#5]
Current Behaviour:
The `lastpass-operator` supports the creation of `Opaque` secrets.

Enhanced behaviour:
Add the flexibility in the `LastPass` custom resource to choose the type of secret to be created.

type: [kubernetes.io/dockerconfigjson](https://github.com/kubernetes/kubernetes/blob/e6214389ca0df8f9418d4f9ada579631b9d7bc02/pkg/apis/core/types.go#L4830)
key: [.dockerconfigjson](https://github.com/kubernetes/kubernetes/blob/e6214389ca0df8f9418d4f9ada579631b9d7bc02/pkg/apis/core/types.go#L4833)

Example secret for docker credentials
```YAML
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: bots
data:
  .dockerconfigjson: ewogICAiYXV0aHMiOnsKICAgICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6ewogICAgICAgICAidXNlcm5hbWUiOiJVc2VybmFtZSIsCiAgICAgICAgICJwYXNzd29yZCI6IlBhc3N3MHJkIiwKICAgICAgICAgImVtYWlsIjoic29tZW9uZUBnbWFpbC5jb20iLAogICAgICAgICAiYXV0aCI6IlZYTmxjbTVoYldVNlVHRnpjM2N3Y21RPSIKICAgICAgfQogICB9Cn0=
```

Example last pass configuration for docker credentials which will be stored as a base64 string under the `.dockerconfigjson` key
```JSON
{
   "auths":{
      "https://index.docker.io/v1/":{
         "username":"Username",
         "password":"Passw0rd",
         "email":"someone@gmail.com",
         "auth":"VXNlcm5hbWU6UGFzc3cwcmQ="
      }
   }
}
```
